server:
  port: 8080

spring:
  application:
    name: vria-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuracion JWT
vria:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration-ms: ${JWT_EXPIRATION}
      refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}
      cookie-secure: ${JWT_COOKIE_SECURE}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE}

logging:
  level:
    org.springframework.security: INFO
    com.vria: DEBUG
